In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
ticker_symbol = "NVDA"
stock = yf.Ticker(ticker_symbol)

In [3]:
income_statement_annual = stock.financials
income_statement_quarterly = stock.quarterly_financials
income_statement = pd.concat([income_statement_annual, income_statement_quarterly], axis=1)
income_statement = income_statement.T
income_statement = income_statement.sort_index()
income_statement.index = income_statement.index.date
income_statement = income_statement.loc[~income_statement.index.duplicated(keep='first')]
income_statement = income_statement.replace(np.NaN, None)
unimportant_columns = [
    'Tax Effect Of Unusual Items',
    'Tax Rate For Calcs',
    'Reconciled Depreciation',
    'Reconciled Cost Of Revenue',
    'Diluted NI Availto Com Stockholders',
    'Basic Average Shares',
    'Operating Revenue',
    'Other Gand A',
    'Net Income Including Noncontrolling Interests',
    'Net Income From Continuing Operation Net Minority Interest',
    'Net Income Continuous Operations',
    'Net Income From Continuing And Discontinued Operation',
    'Interest Expense Non Operating',
    'Interest Income Non Operating',
    'Special Income Charges',
    'Write Off',
    'Gain On Sale Of Security',
    'Total Unusual Items',
    'Total Unusual Items Excluding Goodwill'
]
columns_to_drop = [col for col in unimportant_columns if col in income_statement.columns]
income_statement_cleaned = income_statement.drop(columns=columns_to_drop)
income_statement_cleaned

,Normalized EBITDA,EBITDA,EBIT,Net Interest Income,Interest Expense,Interest Income,Normalized Income,Total Expenses,Total Operating Income As Reported,Diluted Average Shares,...,Other Non Operating Income Expenses,Restructuring And Mergern Acquisition,Net Non Operating Interest Income Expense,Operating Income,Operating Expense,Research And Development,Selling General And Administration,Gross Profit,Cost Of Revenue,Total Revenue
2022-01-31,11351000000.0,11351000000.0,10177000000.0,-207000000.0,236000000.0,29000000.0,9752000000.0,16873000000.0,10041000000.0,25350000000.0,...,107000000.0,0.0,-207000000.0,10041000000.0,7434000000.0,5268000000.0,2166000000.0,17475000000.0,9439000000.0,26914000000.0
2023-01-31,7339000000.0,5986000000.0,4443000000.0,5000000.0,262000000.0,267000000.0,5436870000.0,21397000000.0,4224000000.0,25070000000.0,...,-48000000.0,1353000000.0,5000000.0,5577000000.0,9779000000.0,7339000000.0,2440000000.0,15356000000.0,11618000000.0,26974000000.0
2023-10-31,None,None,None,None,None,None,None,None,None,None,...,None,0.0,None,None,None,None,None,None,None,None
2024-01-31,35583000000.0,35583000000.0,34075000000.0,609000000.0,257000000.0,866000000.0,29760000000.0,27950000000.0,32972000000.0,24940000000.0,...,237000000.0,0.0,609000000.0,32972000000.0,11329000000.0,8675000000.0,2654000000.0,44301000000.0,16621000000.0,60922000000.0
2024-04-30,17753000000.0,17753000000.0,17343000000.0,295000000.0,64000000.0,359000000.0,14881000000.0,9135000000.0,16909000000.0,24890000000.0,...,75000000.0,None,295000000.0,16909000000.0,3497000000.0,2720000000.0,777000000.0,20406000000.0,5638000000.0,26044000000.0
2024-07-31,19708000000.0,19708000000.0,19275000000.0,383000000.0,61000000.0,444000000.0,16599000000.0,11398000000.0,18642000000.0,24848000000.0,...,189000000.0,None,383000000.0,18642000000.0,3932000000.0,3090000000.0,842000000.0,22574000000.0,7466000000.0,30040000000.0
2024-10-31,22855000000.0,22855000000.0,22377000000.0,411000000.0,61000000.0,472000000.0,19309000000.0,13213000000.0,21869000000.0,24774000000.0,...,36000000.0,None,411000000.0,21869000000.0,4287000000.0,3390000000.0,897000000.0,26156000000.0,8926000000.0,35082000000.0
2025-01-31,86137000000.0,86137000000.0,84273000000.0,1539000000.0,247000000.0,1786000000.0,72880000000.0,49044000000.0,81453000000.0,24804000000.0,...,1034000000.0,0.0,1539000000.0,81453000000.0,16405000000.0,12914000000.0,3491000000.0,97858000000.0,32639000000.0,130497000000.0
2025-04-30,22584000000.0,22584000000.0,21973000000.0,452000000.0,63000000.0,515000000.0,18775000000.0,22424000000.0,21638000000.0,24611000000.0,...,-180000000.0,None,452000000.0,21638000000.0,5030000000.0,3989000000.0,1041000000.0,26668000000.0,17394000000.0,44062000000.0

In [4]:
cash_flow_annual = stock.cashflow
cash_flow_quarterly = stock.quarterly_cashflow
cash_flow = pd.concat([cash_flow_annual, cash_flow_quarterly], axis=1)
print(f"Combined Cash Flow Statement for {ticker_symbol}:\n")
cash_flow = cash_flow.T
cash_flow = cash_flow.sort_index()
cash_flow.index = cash_flow.index.date
cash_flow = cash_flow.loc[~cash_flow.index.duplicated(keep='first')]
cash_flow = cash_flow.replace(np.NaN, None)
cash_flow

Combined Cash Flow Statement for NVDA:

,Free Cash Flow,Repurchase Of Capital Stock,Repayment Of Debt,Issuance Of Debt,Capital Expenditure,Interest Paid Supplemental Data,Income Tax Paid Supplemental Data,End Cash Position,Beginning Cash Position,Changes In Cash,...,Depreciation Amortization Depletion,Depreciation And Amortization,Amortization Cash Flow,Amortization Of Intangibles,Depreciation,Operating Gains Losses,Gain Loss On Investment Securities,Net Income From Continuing Operations,Sale Of Business,Gain Loss On Sale Of Business
2021-01-31,None,None,None,4968000000.0,None,None,None,None,None,None,...,None,None,612000000.0,612000000.0,486000000.0,None,None,None,None,None
2022-01-31,8132000000.0,0.0,-1000000000.0,4977000000.0,-976000000.0,246000000.0,396000000.0,1990000000.0,847000000.0,1143000000.0,...,1174000000.0,1174000000.0,563000000.0,563000000.0,611000000.0,-100000000.0,-100000000.0,9752000000.0,None,None
2023-01-31,3808000000.0,-10039000000.0,0.0,0.0,-1833000000.0,254000000.0,1404000000.0,3389000000.0,1990000000.0,1399000000.0,...,1543000000.0,1543000000.0,699000000.0,699000000.0,844000000.0,45000000.0,45000000.0,4368000000.0,None,None
2023-10-31,None,None,0.0,None,None,None,4348000000.0,None,None,None,...,None,None,None,None,None,None,None,None,0.0,69000000.0
2024-01-31,27021000000.0,-9533000000.0,-1250000000.0,0.0,-1069000000.0,252000000.0,6549000000.0,7280000000.0,3389000000.0,3891000000.0,...,1508000000.0,1508000000.0,614000000.0,614000000.0,894000000.0,-238000000.0,-238000000.0,29760000000.0,None,None
2024-04-30,14976000000.0,-7740000000.0,None,None,-369000000.0,None,None,7587000000.0,7280000000.0,307000000.0,...,410000000.0,410000000.0,None,None,None,-69000000.0,-69000000.0,14881000000.0,None,None
2024-07-31,13511000000.0,-7158000000.0,None,None,-977000000.0,None,None,8571000000.0,7587000000.0,984000000.0,...,433000000.0,433000000.0,None,None,None,-195000000.0,-195000000.0,16599000000.0,None,None
2024-10-31,16814000000.0,-10997000000.0,0.0,None,-813000000.0,None,3540000000.0,9107000000.0,8571000000.0,536000000.0,...,478000000.0,478000000.0,None,None,None,-38000000.0,-38000000.0,19309000000.0,66000000.0,-38000000.0
2025-01-31,60853000000.0,-33706000000.0,-1250000000.0,None,-3236000000.0,246000000.0,15118000000.0,8589000000.0,7280000000.0,1309000000.0,...,1864000000.0,1864000000.0,None,None,None,-1030000000.0,-1030000000.0,72880000000.0,None,None
2025-04-30,26187000000.0,-14095000000.0,None,None,-1227000000.0,None,None,15234000000.0,8589000000.0,6645000000.0,...,611000000.0,611000000.0,None,None,None,175000000.0,175000000.0,18775000000.0,None,None

In [5]:
balance_sheet_annual = stock.balance_sheet
balance_sheet_quarterly = stock.quarterly_balance_sheet
balance_sheet = pd.concat([balance_sheet_annual, balance_sheet_quarterly], axis=1)
print(f"Combined Balance Sheet for {ticker_symbol}:\n")
balance_sheet = balance_sheet.T
balance_sheet = balance_sheet.sort_index()
balance_sheet.index = balance_sheet.index.date
balance_sheet = balance_sheet.loc[~balance_sheet.index.duplicated(keep='first')]
balance_sheet = balance_sheet.replace(np.NaN, None)
balance_sheet

Combined Balance Sheet for NVDA:

,Treasury Shares Number,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,Capital Lease Obligations,...,Work In Process,Raw Materials,Receivables,Accounts Receivable,Allowance For Doubtful Accounts Receivable,Gross Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Other Short Term Investments,Cash And Cash Equivalents,Restricted Cash
2021-01-31,13800000000.0,None,None,6116000000.0,None,None,None,None,None,None,...,None,None,None,None,-21000000.0,2450000000.0,None,None,None,None
2022-01-31,None,25060000000.0,25060000000.0,8956000000.0,11831000000.0,19924000000.0,37558000000.0,24494000000.0,19924000000.0,885000000.0,...,692000000.0,791000000.0,4650000000.0,4650000000.0,None,None,21208000000.0,19218000000.0,1990000000.0,None
2023-01-31,None,24661365720.0,24661365720.0,7564000000.0,12031000000.0,16053000000.0,33054000000.0,16510000000.0,16053000000.0,1078000000.0,...,466000000.0,2430000000.0,3827000000.0,3827000000.0,None,None,13296000000.0,9907000000.0,3389000000.0,None
2023-10-31,0.0,None,None,4187000000.0,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2024-01-31,None,24640000000.0,24640000000.0,2429000000.0,11056000000.0,37436000000.0,52687000000.0,33714000000.0,37436000000.0,1347000000.0,...,1505000000.0,1719000000.0,9999000000.0,9999000000.0,None,None,25984000000.0,18704000000.0,7280000000.0,None
2024-04-30,None,24598341970.0,24598341970.0,2123000000.0,11237000000.0,43703000000.0,58852000000.0,38506000000.0,43703000000.0,1527000000.0,...,1625000000.0,1991000000.0,12365000000.0,12365000000.0,None,None,31438000000.0,23851000000.0,7587000000.0,None
2024-07-31,None,24562000000.0,24562000000.0,None,10015000000.0,52583000000.0,66618000000.0,45664000000.0,52583000000.0,1554000000.0,...,2111000000.0,1895000000.0,14132000000.0,14132000000.0,None,None,34800000000.0,26237000000.0,8563000000.0,None
2024-10-31,None,24508000000.0,24508000000.0,None,10225000000.0,60337000000.0,74361000000.0,51161000000.0,60337000000.0,1763000000.0,...,2881000000.0,1846000000.0,17693000000.0,17693000000.0,None,None,38487000000.0,29380000000.0,9107000000.0,None
2025-01-31,None,24477000000.0,24477000000.0,None,10270000000.0,73332000000.0,87790000000.0,62079000000.0,73332000000.0,1807000000.0,...,3399000000.0,3408000000.0,23065000000.0,23065000000.0,None,None,43210000000.0,34621000000.0,8589000000.0,None
2025-04-30,None,24387557065.0,24387557065.0,None,10285000000.0,77576000000.0,92307000000.0,63393000000.0,77576000000.0,1821000000.0,...,5339000000.0,2525000000.0,22132000000.0,22132000000.0,None,None,52691000000.0,37457000000.0,15234000000.0,1000000000.0