In [1]:
import pandas as pd
import numpy as np
import yfinance as yf
import datetime

In [2]:
TICKER='AMZN'

In [3]:
dat = yf.Ticker(TICKER)
dat.info

{'address1': '410 Terry Avenue North',
 'city': 'Seattle',
 'state': 'WA',
 'zip': '98109-5210',
 'country': 'United States',
 'phone': '206 266 1000',
 'website': 'https://www.aboutamazon.com',
 'industry': 'Internet Retail',
 'industryKey': 'internet-retail',
 'industryDisp': 'Internet Retail',
 'sector': 'Consumer Cyclical',
 'sectorKey': 'consumer-cyclical',
 'sectorDisp': 'Consumer Cyclical',
 'longBusinessSummary': "Amazon.com, Inc. engages in the retail sale of consumer products, advertising, and subscriptions service through online and physical stores in North America and internationally. The company operates through three segments: North America, International, and Amazon Web Services (AWS). It also manufactures and sells electronic devices, including Kindle, fire tablets, fire TVs, echo, ring, blink, and eero; and develops and produces media content. In addition, the company offers programs that enable sellers to sell their products in its stores; and programs that allow authors, independent publishers, musicians, filmmakers, Twitch streamers, skill and app developers, and others to publish and sell content. Further, it provides compute, storage, database, analytics, machine learning, and other services, as well as advertising services through programs, such as sponsored ads, display, and video advertising. Additionally, the company offers Amazon Prime, a membership program. The company's products offered through its stores include merchandise and content purchased for resale and products offered by third-party sellers. It serves consumers, sellers, developers, enterprises, content creators, advertisers, and employees. Amazon.com, Inc. was incorporated in 1994 and is headquartered in Seattle, Washington.",
 'fullTimeEmployees': 1560000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jeffrey P. Bezos',
   'age': 60,
   'title': 'Founder & Executive Chairman',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 1681840,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Andrew R. Jassy',
   'age': 56,
   'title': 'President, CEO & Director',
   'yearBorn': 1968,
   'fiscalYear': 2024,
   'totalPay': 1596889,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Brian T. Olsavsky',
   'age': 60,
   'title': 'Senior VP & CFO',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 371900,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. David A. Zapolsky J.D.',
   'age': 60,
   'title': 'Senior VP, Chief Global Affairs & Legal Officer',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 371900,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Douglas J. Herrington',
   'age': 57,
   'title': 'Chief Executive Officer of Worldwide Amazon Stores',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 386435,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew S. Garman',
   'age': 47,
   'title': 'Chief Executive Officer of Amazon Web Series',
   'yearBorn': 1977,
   'fiscalYear': 2024,
   'totalPay': 384275,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Shelley L. Reynolds',
   'age': 59,
   'title': 'VP, Worldwide Controller & Principal Accounting Officer',
   'yearBorn': 1965,
   'fiscalYear': 2024,
   'totalPay': 163200,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Dr. Werner  Vogels',
   'title': 'Chief Technology Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Dave  Fildes',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Anuradha  Aggarwal',
   'title': 'CMO & Director of User Growth',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 8,
 'compensationRisk': 10,
 'shareHolderRightsRisk': 3,
 'overallRisk': 9,
 'governanceEpochDate': 1748736000,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=97664&p=irol-irhome',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 223.47,
 'open': 223.915,
 'dayLow': 218.43,
 'dayHigh': 224.0,
 'regularMarketPreviousClose': 223.47,
 'regularMarketOpen': 223.915,
 'regularMarketDayLow': 218.43,
 'regularMarketDayHigh': 224.0,
 'payoutRatio': 0.0,
 'beta': 1.334,
 'trailingPE': 35.726387,
 'forwardPE': 35.668293,
 'volume': 44865085,
 'regularMarketVolume': 44865085,
 'averageVolume': 44588243,
 'averageVolume10days': 48073030,
 'averageDailyVolume10Day': 48073030,
 'bid': 219.35,
 'ask': 219.47,
 'bidSize': 4,
 'askSize': 2,
 'marketCap': 2328813371392,
 'fiftyTwoWeekLow': 151.61,
 'fiftyTwoWeekHigh': 242.52,
 'priceToSalesTrailing12Months': 3.5810654,
 'fiftyDayAverage': 206.3758,
 'twoHundredDayAverage': 206.01535,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 2392509644800,
 'profitMargins': 0.1014,
 'floatShares': 9571703330,
 'sharesOutstanding': 10616399872,
 'sharesShort': 61836013,
 'sharesShortPriorMonth': 71501108,
 'sharesShortPreviousMonthDate': 1747267200,
 'dateShortInterest': 1749772800,
 'sharesPercentSharesOut': 0.0058,
 'heldPercentInsiders': 0.08721,
 'heldPercentInstitutions': 0.65449,
 'shortRatio': 1.62,
 'shortPercentOfFloat': 0.0064,
 'impliedSharesOutstanding': 10616399872,
 'bookValue': 28.82,
 'priceToBook': 7.611381,
 'lastFiscalYearEnd': 1735603200,
 'nextFiscalYearEnd': 1767139200,
 'mostRecentQuarter': 1743379200,
 'earningsQuarterlyGrowth': 0.642,
 'netIncomeToCommon': 65943998464,
 'trailingEps': 6.14,
 'forwardEps': 6.15,
 'lastSplitFactor': '20:1',
 'lastSplitDate': 1654473600,
 'enterpriseToRevenue': 3.679,
 'enterpriseToEbitda': 18.966,
 '52WeekChange': 0.09795284,
 'SandP52WeekChange': 0.10500872,
 'quoteType': 'EQUITY',
 'currentPrice': 219.36,
 'targetHighPrice': 305.0,
 'targetLowPrice': 195.0,
 'targetMeanPrice': 241.81862,
 'targetMedianPrice': 240.0,
 'recommendationMean': 1.37143,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 65,
 'totalCash': 94564999168,
 'totalCashPerShare': 8.907,
 'ebitda': 126144004096,
 'totalDebt': 157952999424,
 'quickRatio': 0.807,
 'currentRatio': 1.048,
 'totalRevenue': 650313007104,
 'debtToEquity': 51.641,
 'revenuePerShare': 61.785,
 'returnOnAssets': 0.07632,
 'returnOnEquity': 0.2524,
 'grossProfits': 319681986560,
 'freeCashflow': 39273500672,
 'operatingCashflow': 113903001600,
 'earningsGrowth': 0.622,
 'revenueGrowth': 0.086,
 'grossMargins': 0.49158,
 'ebitdaMargins': 0.19397,
 'operatingMargins': 0.11823,
 'financialCurrency': 'USD',
 'symbol': 'AMZN',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'postMarketTime': 1752019199,
 'regularMarketTime': 1752004802,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_18749',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': -1.83917,
 'regularMarketPrice': 219.36,
 'priceEpsCurrentYear': 35.298264,
 'fiftyDayAverageChange': 12.984207,
 'fiftyDayAverageChangePercent': 0.06291536,
 'twoHundredDayAverageChange': 13.34465,
 'twoHundredDayAverageChangePercent': 0.06477503,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.4 - Strong Buy',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 863703000000,
 'postMarketChangePercent': 0.150438,
 'postMarketPrice': 219.69,
 'postMarketChange': 0.330002,
 'regularMarketChange': -4.11,
 'regularMarketDayRange': '218.43 - 224.0',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 44588243,
 'fiftyTwoWeekLowChange': 67.75,
 'fiftyTwoWeekLowChangePercent': 0.44687027,
 'fiftyTwoWeekRange': '151.61 - 242.52',
 'fiftyTwoWeekHighChange': -23.160004,
 'fiftyTwoWeekHighChangePercent': -0.095497295,
 'fiftyTwoWeekChangePercent': 9.795284,
 'earningsTimestamp': 1746129660,
 'earningsTimestampStart': 1754596800,
 'earningsTimestampEnd': 1754596800,
 'earningsCallTimestampStart': 1746133200,
 'earningsCallTimestampEnd': 1746133200,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 6.14,
 'epsForward': 6.15,
 'epsCurrentYear': 6.21447,
 'shortName': 'Amazon.com, Inc.',
 'longName': 'Amazon.com, Inc.',
 'marketState': 'PREPRE',
 'cryptoTradeable': False,
 'displayName': 'Amazon.com',
 'trailingPegRatio': 2.8319}

In [4]:
dat.calendar

{'Earnings Date': [datetime.date(2025, 8, 8)],
 'Earnings High': 1.54,
 'Earnings Low': 1.0,
 'Earnings Average': 1.3024,
 'Revenue High': 163623000000,
 'Revenue Low': 159004000000,
 'Revenue Average': 161784586040}

In [5]:
dat.analyst_price_targets

{'current': 219.36,
 'high': 305.0,
 'low': 195.0,
 'mean': 241.81862,
 'median': 240.0}

In [6]:
dat.quarterly_income_stmt

,2025-03-31,2024-12-31,2024-09-30,2024-06-30,2024-03-31
Tax Effect Of Unusual Items,584272614.050464,59714081.166943,-2700449.076897,4636274.188258,-460982977.740122
Tax Rate For Calcs,0.210019,0.104032,0.150025,0.115907,0.190018
Normalized EBITDA,33700000000.0,37976000000.0,32100000000.0,27832000000.0,27737000000.0
Total Unusual Items,2782000000.0,574000000.0,-18000000.0,40000000.0,-2426000000.0
Total Unusual Items Excluding Goodwill,2782000000.0,574000000.0,-18000000.0,40000000.0,-2426000000.0
Net Income From Continuing Operation Net Minority Interest,17127000000.0,20004000000.0,15328000000.0,13485000000.0,10431000000.0
Reconciled Depreciation,14262000000.0,15631000000.0,13442000000.0,12038000000.0,11684000000.0
Reconciled Cost Of Revenue,76976000000.0,98893000000.0,80977000000.0,73785000000.0,72633000000.0
EBITDA,36482000000.0,38550000000.0,32082000000.0,27872000000.0,25311000000.0
EBIT,22220000000.0,22919000000.0,18640000000.0,15834000000.0,13627000000.0
Net Interest Income,525000000.0,678000000.0,653000000.0,591000000.0,349000000.0
Interest Expense,541000000.0,570000000.0,603000000.0,589000000.0,644000000.0
Interest Income,1066000000.0,1248000000.0,1256000000.0,1180000000.0,993000000.0
Normalized Income,14929272614.050465,19489714081.166943,15343299550.923103,13449636274.188257,12396017022.259878
Net Income From Continuing And Discontinued Operation,17127000000.0,20004000000.0,15328000000.0,13485000000.0,10431000000.0
Total Expenses,137262000000.0,166589000000.0,141466000000.0,133305000000.0,128006000000.0
Total Operating Income As Reported,18405000000.0,21203000000.0,17411000000.0,14672000000.0,15307000000.0
Diluted Average Shares,10793000000.0,10771000000.0,10735000000.0,10708000000.0,10670000000.0
Basic Average Shares,10603000000.0,10552000000.0,10501000000.0,10447000000.0,10393000000.0
Diluted EPS,1.59,1.86,1.43,1.26,0.98
Basic EPS,1.62,1.9,1.46,1.29,1.0
Diluted NI Availto Com Stockholders,17127000000.0,20004000000.0,15328000000.0,13485000000.0,10431000000.0
Net Income Common Stockholders,17127000000.0,20004000000.0,15328000000.0,13485000000.0,10431000000.0
Net Income,17127000000.0,20004000000.0,15328000000.0,13485000000.0,10431000000.0
Net Income Including Noncontrolling Interests,17127000000.0,20004000000.0,15328000000.0,13485000000.0,10431000000.0
Net Income Continuous Operations,17127000000.0,20004000000.0,15328000000.0,13485000000.0,10431000000.0
Earnings From Equity Interest Net Of Tax,1000000.0,-20000000.0,-3000000.0,7000000.0,-85000000.0
Tax Provision,4553000000.0,2325000000.0,2706000000.0,1767000000.0,2467000000.0
Pretax Income,21679000000.0,22349000000.0,18037000000.0,15245000000.0,12983000000.0
Other Income Expense,2749000000.0,468000000.0,-27000000.0,-18000000.0,-2674000000.0
Other Non Operating Income Expenses,-33000000.0,-106000000.0,-9000000.0,-58000000.0,-248000000.0
Gain On Sale Of Security,2782000000.0,574000000.0,-18000000.0,40000000.0,-2426000000.0
Net Non Operating Interest Income Expense,525000000.0,678000000.0,653000000.0,591000000.0,349000000.0
Interest Expense Non Operating,541000000.0,570000000.0,603000000.0,589000000.0,644000000.0
Interest Income Non Operating,1066000000.0,1248000000.0,1256000000.0,1180000000.0,993000000.0
Operating Income,18405000000.0,21203000000.0,17411000000.0,14672000000.0,15307000000.0
Operating Expense,60286000000.0,67696000000.0,60489000000.0,59520000000.0,55373000000.0
Other Operating Expenses,47895000000.0,51709000000.0,47167000000.0,45967000000.0,42969000000.0
Selling General And Administration,12391000000.0,15987000000.0,13322000000.0,13553000000.0,12404000000.0
Selling And Marketing Expense,9763000000.0,13124000000.0,10609000000.0,10512000000.0,9662000000.0
General And Administrative Expense,2628000000.0,2863000000.0,2713000000.0,3041000000.0,2742000000.0
Other Gand A,2628000000.0,2863000000.0,2713000000.0,3041000000.0,2742000000.0
Gross Profit,78691000000.0,88899000000.0,77900000000.0,74192000000.0,70680000000.0
Cost Of Revenue,76976000000.0,98893000000.0,80977000000.0,73785000000.0,72633000000.0
Total Revenue,155667000000.0,187792000000.0,158877000000.0,147977000000.0,143313000000.0
Operating Revenue,155667000000.0,187792000000.0,158877000000.0,147977000000.0,143313000000.0

In [7]:
dat.option_chain(dat.options[0]).calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AMZN250711C00105000,2025-07-08 15:45:41+00:00,105.0,115.34,0.0,0.00,0.0,0.0,143.0,0,0.000010,True,REGULAR,USD
1,AMZN250711C00110000,2025-07-07 13:40:19+00:00,110.0,113.18,0.0,0.00,0.0,0.0,1.0,0,0.000010,True,REGULAR,USD
2,AMZN250711C00115000,2025-06-27 18:22:28+00:00,115.0,103.14,0.0,0.00,0.0,0.0,20.0,0,0.000010,True,REGULAR,USD
3,AMZN250711C00120000,2025-07-08 19:11:21+00:00,120.0,99.82,0.0,0.00,0.0,0.0,1.0,0,0.000010,True,REGULAR,USD
4,AMZN250711C00125000,2025-07-07 17:44:35+00:00,125.0,98.10,0.0,0.00,0.0,0.0,3.0,0,0.000010,True,REGULAR,USD
5,AMZN250711C00130000,2025-07-02 19:40:28+00:00,130.0,90.17,0.0,0.00,0.0,0.0,NaN,0,0.000010,True,REGULAR,USD
6,AMZN250711C00135000,2025-07-03 15:23:03+00:00,135.0,87.70,0.0,0.00,0.0,0.0,19.0,0,0.000010,True,REGULAR,USD
7,AMZN250711C00140000,2025-07-03 15:23:05+00:00,140.0,82.80,0.0,0.00,0.0,0.0,10.0,0,0.000010,True,REGULAR,USD
8,AMZN250711C00145000,2025-06-20 15:38:14+00:00,145.0,65.97,0.0,0.00,0.0,0.0,1.0,0,0.000010,True,REGULAR,USD
9,AMZN250711C00150000,2025-07-08 17:10:12+00:00,150.0,70.54,0.0,0.00,0.0,0.0,5000.0,0,0.000010,True,REGULAR,USD
10,AMZN250711C00155000,2025-07-03 16:34:49+00:00,155.0,68.60,0.0,0.00,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD
11,AMZN250711C00160000,2025-05-29 19:04:21+00:00,160.0,46.61,62.5,63.95,0.0,0.0,5.0,5,3.218752,True,REGULAR,USD
12,AMZN250711C00165000,2025-07-08 17:02:33+00:00,165.0,55.70,0.0,0.00,0.0,0.0,10.0,0,0.000010,True,REGULAR,USD
13,AMZN250711C00170000,2025-07-08 14:20:39+00:00,170.0,51.57,0.0,0.00,0.0,0.0,21.0,0,0.000010,True,REGULAR,USD
14,AMZN250711C00175000,2025-07-08 14:03:36+00:00,175.0,47.10,0.0,0.00,0.0,0.0,6.0,0,0.000010,True,REGULAR,USD
15,AMZN250711C00180000,2025-07-08 15:41:41+00:00,180.0,40.29,0.0,0.00,0.0,0.0,4.0,0,0.000010,True,REGULAR,USD
16,AMZN250711C00185000,2025-07-08 17:46:20+00:00,185.0,35.58,0.0,0.00,0.0,0.0,95.0,0,0.000010,True,REGULAR,USD
17,AMZN250711C00187500,2025-06-27 15:58:45+00:00,187.5,33.24,0.0,0.00,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD
18,AMZN250711C00190000,2025-07-08 19:45:12+00:00,190.0,29.67,0.0,0.00,0.0,0.0,19.0,0,0.000010,True,REGULAR,USD
19,AMZN250711C00192500,2025-07-08 14:26:51+00:00,192.5,29.03,0.0,0.00,0.0,0.0,1.0,0,0.000010,True,REGULAR,USD
20,AMZN250711C00195000,2025-07-08 17:19:01+00:00,195.0,25.53,0.0,0.00,0.0,0.0,28.0,0,0.000010,True,REGULAR,USD
21,AMZN250711C00197500,2025-07-07 17:35:43+00:00,197.5,25.78,0.0,0.00,0.0,0.0,7.0,0,0.000010,True,REGULAR,USD
22,AMZN250711C00200000,2025-07-08 19:47:55+00:00,200.0,19.87,0.0,0.00,0.0,0.0,106.0,0,0.000010,True,REGULAR,USD
23,AMZN250711C00202500,2025-07-08 14:08:45+00:00,202.5,18.81,0.0,0.00,0.0,0.0,4.0,0,0.000010,True,REGULAR,USD
24,AMZN250711C00205000,2025-07-08 19:47:55+00:00,205.0,14.92,0.0,0.00,0.0,0.0,179.0,0,0.000010,True,REGULAR,USD
25,AMZN250711C00207500,2025-07-08 19:20:54+00:00,207.5,12.95,0.0,0.00,0.0,0.0,23.0,0,0.000010,True,REGULAR,USD
26,AMZN250711C00210000,2025-07-08 19:58:26+00:00,210.0,9.65,0.0,0.00,0.0,0.0,351.0,0,0.000010,True,REGULAR,USD
27,AMZN250711C00212500,2025-07-08 19:58:26+00:00,212.5,7.37,0.0,0.00,0.0,0.0,318.0,0,0.000010,True,REGULAR,USD
28,AMZN250711C00215000,2025-07-08 19:59:50+00:00,215.0,5.40,0.0,0.00,0.0,0.0,1853.0,0,0.000010,True,REGULAR,USD
29,AMZN250711C00217500,2025-07-08 19:59:57+00:00,217.5,3.70,0.0,0.00,0.0,0.0,2776.0,0,0.000010,True,REGULAR,USD
30,AMZN250711C00220000,2025-07-08 19:59:59+00:00,220.0,2.21,0.0,0.00,0.0,0.0,29038.0,0,0.007822,False,REGULAR,USD
31,AMZN250711C00222500,2025-07-08 19:59:57+00:00,222.5,1.25,0.0,0.00,0.0,0.0,34263.0,0,0.031260,False,REGULAR,USD
32,AMZN250711C00225000,2025-07-08 19:59:59+00:00,225.0,0.61,0.0,0.00,0.0,0.0,48590.0,0,0.062509,False,REGULAR,USD
33,AMZN250711C00227500,2025-07-08 19:59:59+00:00,227.5,0.29,0.0,0.00,0.0,0.0,14458.0,0,0.125009,False,REGULAR,USD
34,AMZN250711C00230000,2025-07-08 19:59:57+00:00,230.0,0.15,0.0,0.00,0.0,0.0,22831.0,0,0.125009,False,REGULAR,USD
35,AMZN250711C00232500,2025-07-08 19:59:48+00:00,232.5,0.08,0.0,0.00,0.0,0.0,5572.0,0,0.125009,False,REGULAR,USD
36,AMZN250711C00235000,2025-07-08 19:59:47+00:00,235.0,0.05,0.0,0.00,0.0,0.0,9357.0,0,0.125009,False,REGULAR,USD
37,AMZN250711C00237500,2025-07-08 19:58:45+00:00,237.5,0.04,0.0,0.00,0.0,0.0,974.0,0,0.250007,False,REGULAR,USD
38,AMZN250711C00240000,2025-07-08 19:56:22+00:00,240.0,0.03,0.0,0.00,0.0,0.0,6536.0,0,0.250007,False,REGULAR,USD
39,AMZN250711C00242500,2025-07-08 19:32:55+00:00,242.5,0.01,0.0,0.00,0.0,0.0,79.0,0,0.250007,False,REGULAR,USD
40,AMZN250711C00245000,2025-07-08 19:31:46+00:00,245.0,0.02,0.0,0.00,0.0,0.0,3373.0,0,0.250007,False,REGULAR,USD
41,AMZN250711C00250000,2025-07-08 19:52:28+00:00,250.0,0.01,0.0,0.00,0.0,0.0,631.0,0,0.250007,False,REGULAR,USD
42,AMZN250711C00255000,2025-07-07 18:24:34+00:00,255.0,0.01,0.0,0.00,0.0,0.0,856.0,0,0.250007,False,REGULAR,USD
43,AMZN250711C00260000,2025-07-08 17:34:51+00:00,260.0,0.01,0.0,0.00,0.0,0.0,10.0,0,0.500005,False,REGULAR,USD
44,AMZN250711C00265000,2025-07-08 18:43:39+00:00,265.0,0.01,0.0,0.00,0.0,0.0,2.0,0,0.500005,False,REGULAR,USD
45,AMZN250711C00270000,2025-07-08 14:55:38+00:00,270.0,0.01,0.0,0.00,0.0,0.0,60.0,0,0.500005,False,REGULAR,USD
46,AMZN250711C00275000,2025-07-07 13:31:02+00:00,275.0,0.01,0.0,0.00,0.0,0.0,1.0,0,0.500005,False,REGULAR,USD
47,AMZN250711C00280000,2025-07-08 13:30:00+00:00,280.0,0.01,0.0,0.00,0.0,0.0,1.0,0,0.500005,False,REGULAR,USD
48,AMZN250711C00285000,2025-07-07 13:30:03+00:00,285.0,0.01,0.0,0.00,0.0,0.0,4.0,0,0.500005,False,REGULAR,USD

In [9]:
import json

# export info as json
with open(f"data/info_from_yfinance/{TICKER}_info.json".lower(), "w") as f:
	json.dump(dat.info, f, indent=4)

In [10]:
dat.balance_sheet

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Treasury Shares Number,515000000.0,515000000.0,515000000.0,460000000.0,NaN
Ordinary Shares Number,10593000000.0,10383000000.0,10242000000.0,10180000000.0,NaN
Share Issued,11108000000.0,10898000000.0,10757000000.0,10640000000.0,NaN
Net Debt,NaN,NaN,13262000000.0,12524000000.0,NaN
Total Debt,130900000000.0,135611000000.0,140118000000.0,116395000000.0,NaN
...,...,...,...,...,...
Allowance For Doubtful Accounts Receivable,-2000000000.0,-1700000000.0,-1400000000.0,-1100000000.0,NaN
Gross Accounts Receivable,57451000000.0,53953000000.0,43760000000.0,33991000000.0,NaN
Cash Cash Equivalents And Short Term Investments,101202000000.0,86780000000.0,70026000000.0,96049000000.0,NaN
Other Short Term Investments,22423000000.0,13393000000.0,16138000000.0,59829000000.0,NaN
Cash And Cash Equivalents,78779000000.0,73387000000.0,53888000000.0,36220000000.0,NaN

In [11]:
dat.income_stmt

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Tax Effect Of Unusual Items,-246971244.935436,211380035.679101,-3415860000.0,1839997169.143666,NaN
Tax Rate For Calcs,0.135031,0.189579,0.21,0.12558,NaN
Normalized EBITDA,125644000000.0,88287000000.0,54618000000.0,59741000000.0,NaN
Total Unusual Items,-1829000000.0,1115000000.0,-16266000000.0,14652000000.0,NaN
Total Unusual Items Excluding Goodwill,-1829000000.0,1115000000.0,-16266000000.0,14652000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,59248000000.0,30425000000.0,-2722000000.0,33364000000.0,NaN
Reconciled Depreciation,52795000000.0,48663000000.0,41921000000.0,34433000000.0,NaN
Reconciled Cost Of Revenue,326288000000.0,304739000000.0,288831000000.0,272344000000.0,NaN
EBITDA,123815000000.0,89402000000.0,38352000000.0,74393000000.0,NaN
EBIT,71020000000.0,40739000000.0,-3569000000.0,39960000000.0,NaN
Net Interest Income,2271000000.0,-233000000.0,-1378000000.0,-1361000000.0,NaN
Interest Expense,2406000000.0,3182000000.0,2367000000.0,1809000000.0,NaN
Interest Income,4677000000.0,2949000000.0,989000000.0,448000000.0,NaN
Normalized Income,60830028755.064568,29521380035.6791,10128140000.0,20551997169.143665,NaN
Net Income From Continuing And Discontinued Operation,59248000000.0,30425000000.0,-2722000000.0,33364000000.0,NaN
Total Expenses,569366000000.0,537933000000.0,501735000000.0,444943000000.0,NaN
Total Operating Income As Reported,68593000000.0,36852000000.0,12248000000.0,24879000000.0,NaN
Diluted Average Shares,10721000000.0,10492000000.0,10189000000.0,10300000000.0,NaN
Basic Average Shares,10473000000.0,10304000000.0,10189000000.0,10120000000.0,NaN
Diluted EPS,5.53,2.9,-0.27,3.2405,NaN
Basic EPS,5.66,2.95,-0.27,3.298,NaN
Diluted NI Availto Com Stockholders,59248000000.0,30425000000.0,-2722000000.0,33364000000.0,NaN
Net Income Common Stockholders,59248000000.0,30425000000.0,-2722000000.0,33364000000.0,NaN
Net Income,59248000000.0,30425000000.0,-2722000000.0,33364000000.0,NaN
Net Income Including Noncontrolling Interests,59248000000.0,30425000000.0,-2722000000.0,33364000000.0,NaN
Net Income Continuous Operations,59248000000.0,30425000000.0,-2722000000.0,33364000000.0,NaN
Earnings From Equity Interest Net Of Tax,-101000000.0,-12000000.0,-3000000.0,4000000.0,NaN
Tax Provision,9265000000.0,7120000000.0,-3217000000.0,4791000000.0,NaN
Pretax Income,68614000000.0,37557000000.0,-5936000000.0,38151000000.0,NaN
Other Income Expense,-2250000000.0,938000000.0,-16806000000.0,14633000000.0,NaN
Other Non Operating Income Expenses,-421000000.0,-177000000.0,-540000000.0,-19000000.0,NaN
Gain On Sale Of Security,-1829000000.0,1115000000.0,-16266000000.0,14652000000.0,NaN
Net Non Operating Interest Income Expense,2271000000.0,-233000000.0,-1378000000.0,-1361000000.0,NaN
Interest Expense Non Operating,2406000000.0,3182000000.0,2367000000.0,1809000000.0,NaN
Interest Income Non Operating,4677000000.0,2949000000.0,989000000.0,448000000.0,NaN
Operating Income,68593000000.0,36852000000.0,12248000000.0,24879000000.0,NaN
Operating Expense,243078000000.0,233194000000.0,212904000000.0,172599000000.0,NaN
Other Operating Expenses,187812000000.0,177008000000.0,158775000000.0,131225000000.0,NaN
Research And Development,NaN,NaN,NaN,NaN,42740000000.0
Selling General And Administration,55266000000.0,56186000000.0,54129000000.0,41374000000.0,NaN
Selling And Marketing Expense,43907000000.0,44370000000.0,42238000000.0,32551000000.0,NaN
General And Administrative Expense,11359000000.0,11816000000.0,11891000000.0,8823000000.0,NaN
Other Gand A,11359000000.0,11816000000.0,11891000000.0,8823000000.0,NaN
Gross Profit,311671000000.0,270046000000.0,225152000000.0,197478000000.0,NaN
Cost Of Revenue,326288000000.0,304739000000.0,288831000000.0,272344000000.0,NaN
Total Revenue,637959000000.0,574785000000.0,513983000000.0,469822000000.0,NaN
Operating Revenue,637959000000.0,574785000000.0,513983000000.0,469822000000.0,NaN

In [12]:
dat.news[0]

{'id': '318e4d5f-4c1e-32a8-83a8-0371b473abfa',
 'content': {'id': '318e4d5f-4c1e-32a8-83a8-0371b473abfa',
  'contentType': 'VIDEO',
  'title': "Walmart ramps up e-commerce to rival Amazon's Prime Day event",
  'description': '<p>Walmart (<a data-i13n="cpos:1;pos:1" href="https://finance.yahoo.com/quote/WMT">WMT</a>) is trying to outpace Amazon (<a data-i13n="cpos:2;pos:1" href="https://finance.yahoo.com/quote/AMZN">AMZN</a>) this year with "Walmart Deals Week," a six-day savings event (two days longer than Amazon\'s Prime Day sales event).</p>\n<p>Yahoo Finance Senior Reporter <a data-i13n="cpos:3;pos:1" href="https://finance.yahoo.com/author/brooke-dipalma/">Brooke DiPalma</a> breaks down Walmart\'s latest push to grow its e-commerce and grocery businesses.</p>\n<p>To watch more expert insights and analysis on the latest market action, check out more Market Domination\xa0<a data-i13n="cpos:4;pos:1" href="https://finance.yahoo.com/videos/series/market-domination/">here</a>.</p>',
  'summary': 'Walmart (WMT) is trying to outpace Amazon (AMZN) this year with "Walmart Deals Week," a six-day savings event (two days longer than Amazon\'s Prime Day sales event). Yahoo Finance Senior Reporter Brooke DiPalma breaks down Walmart\'s latest push to grow its e-commerce and grocery businesses. To watch more expert insights and analysis on the latest market action, check out more Market Domination&nbsp;here.',
  'pubDate': '2025-07-08T20:27:51Z',
  'displayTime': '',
  'isHosted': True,
  'bypassModal': False,
  'previewUrl': None,
  'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-07/349b1cb0-5c38-11f0-8fce-b4d5c1627e54',
   'originalWidth': 4664,
   'originalHeight': 2626,
   'caption': '',
   'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/T5uM4uXrJPTAnJZrDFHVwg--~B/aD0yNjI2O3c9NDY2NDthcHBpZD15dGFjaHlvbg--/https://s.yimg.com/os/creatr-uploaded-images/2025-07/349b1cb0-5c38-11f0-8fce-b4d5c1627e54',
     'width': 4664,
     'height': 2626,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/JOmFY9BdH2OTzytWHaXWNA--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://s.yimg.com/os/creatr-uploaded-images/2025-07/349b1cb0-5c38-11f0-8fce-b4d5c1627e54',
     'width': 170,
     'height': 128,
     'tag': '170x128'}]},
  'provider': {'displayName': 'Yahoo Finance Video',
   'url': 'https://finance.yahoo.com/'},
  'canonicalUrl': {'url': 'https://finance.yahoo.com/video/walmart-ramps-e-commerce-rival-202751701.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/walmart-ramps-e-commerce-rival-202751701.html',
   'site': 'finance',
   'region': 'US',
   'lang': 'en-US'},
  'metadata': {'editorsPick': True},
  'finance': {'premiumFinance': {'isPremiumNews': False,
    'isPremiumFreeNews': False}},
  'storyline': {'storylineItems': [{'content': {'id': '6c2fb8e9-6fff-4d94-ba5a-dda94f4339fe',
      'contentType': 'STORY',
      'isHosted': True,
      'title': 'Stock market today: Dow, S&P 500 slip as Trump stays firm on August tariff deadline, announces copper duties',
      'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-07/b9f1ba60-5b55-11f0-beff-b7020af20aa9',
       'originalWidth': 8192,
       'originalHeight': 5464,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance',
       'sourceId': 'yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-slip-as-trump-stays-firm-on-august-tariff-deadline-announces-copper-duties-200133528.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-slip-as-trump-stays-firm-on-august-tariff-deadline-announces-copper-duties-200133528.html'}}},
    {'content': {'id': '9768e3f2-5c58-4511-a4e7-2bc4aedca0f7',
      'contentType': 'STORY',
      'isHosted': True,
      'title': "Amazon's Prime Day event is on. How Walmart is hoping to crash the party.",
      'thumbnail': {'originalUrl': 'https://s.yimg.com/os/creatr-uploaded-images/2025-05/fd0d4c50-2d0c-11f0-be77-01eca3cef7c3',
       'originalWidth': 3498,
       'originalHeight': 1941,
       'caption': '',
       'resolutions': None},
      'provider': {'displayName': 'Yahoo Finance',
       'sourceId': 'yahoofinance.com'},
      'previewUrl': None,
      'providerContentUrl': '',
      'canonicalUrl': {'url': 'https://finance.yahoo.com/news/amazons-prime-day-event-is-on-how-walmart-is-hoping-to-crash-the-party-192421273.html'},
      'clickThroughUrl': {'url': 'https://finance.yahoo.com/news/amazons-prime-day-event-is-on-how-walmart-is-hoping-to-crash-the-party-192421273.html'}}}]}}}

In [13]:
dat.quarterly_balance_sheet

,2025-03-31,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31
Treasury Shares Number,515000000.0,515000000.0,515000000.0,515000000.0,515000000.0,NaN
Ordinary Shares Number,10613000000.0,10593000000.0,10511000000.0,10490000000.0,10403000000.0,NaN
Share Issued,11128000000.0,11108000000.0,11026000000.0,11005000000.0,10918000000.0,NaN
Total Debt,133245000000.0,130900000000.0,134692000000.0,132973000000.0,134686000000.0,NaN
Tangible Book Value,282778000000.0,254294000000.0,236070000000.0,213568000000.0,193891000000.0,NaN
Invested Capital,359241000000.0,338593000000.0,314041000000.0,291336000000.0,274295000000.0,NaN
Working Capital,8474000000.0,11436000000.0,14315000000.0,15135000000.0,11024000000.0,NaN
Net Tangible Assets,282778000000.0,254294000000.0,236070000000.0,213568000000.0,193891000000.0,NaN
Capital Lease Obligations,79871000000.0,78277000000.0,79802000000.0,78084000000.0,77052000000.0,NaN
Common Stock Equity,305867000000.0,285970000000.0,259151000000.0,236447000000.0,216661000000.0,NaN
Total Capitalization,359241000000.0,338593000000.0,314041000000.0,291336000000.0,274295000000.0,NaN
Total Equity Gross Minority Interest,305867000000.0,285970000000.0,259151000000.0,236447000000.0,216661000000.0,NaN
Stockholders Equity,305867000000.0,285970000000.0,259151000000.0,236447000000.0,216661000000.0,NaN
Gains Losses Not Affecting Retained Earnings,-914000000.0,-34000000.0,-1918000000.0,-3993000000.0,-3598000000.0,NaN
Other Equity Adjustments,-914000000.0,-34000000.0,-1918000000.0,-3993000000.0,-3598000000.0,NaN
Treasury Stock,7837000000.0,7837000000.0,7837000000.0,7837000000.0,7837000000.0,NaN
Retained Earnings,189993000000.0,172866000000.0,152862000000.0,137534000000.0,124049000000.0,NaN
Additional Paid In Capital,124514000000.0,120864000000.0,115934000000.0,110633000000.0,103938000000.0,NaN
Capital Stock,111000000.0,111000000.0,110000000.0,110000000.0,109000000.0,NaN
Common Stock,111000000.0,111000000.0,110000000.0,110000000.0,109000000.0,NaN
Preferred Stock,0.0,0.0,0.0,0.0,0.0,NaN
Total Liabilities Net Minority Interest,337389000000.0,338924000000.0,325475000000.0,318371000000.0,314308000000.0,NaN
Total Non Current Liabilities Net Minority Interest,161218000000.0,159493000000.0,163998000000.0,160199000000.0,161343000000.0,NaN
Other Non Current Liabilities,27973000000.0,28593000000.0,29306000000.0,27226000000.0,26657000000.0,NaN
Long Term Debt And Capital Lease Obligation,133245000000.0,130900000000.0,134692000000.0,132973000000.0,134686000000.0,NaN
Long Term Capital Lease Obligation,79871000000.0,78277000000.0,79802000000.0,78084000000.0,77052000000.0,NaN
Long Term Debt,53374000000.0,52623000000.0,54890000000.0,54889000000.0,57634000000.0,NaN
Current Liabilities,176171000000.0,179431000000.0,161477000000.0,158172000000.0,152965000000.0,NaN
Current Deferred Liabilities,20599000000.0,18103000000.0,16305000000.0,16004000000.0,15927000000.0,NaN
Current Deferred Revenue,20599000000.0,18103000000.0,16305000000.0,16004000000.0,15927000000.0,NaN
Payables And Accrued Expenses,155572000000.0,161328000000.0,145172000000.0,142168000000.0,137038000000.0,NaN
Current Accrued Expenses,66331000000.0,66965000000.0,60602000000.0,60351000000.0,63970000000.0,NaN
Payables,89241000000.0,94363000000.0,84570000000.0,81817000000.0,73068000000.0,NaN
Accounts Payable,89241000000.0,94363000000.0,84570000000.0,81817000000.0,73068000000.0,NaN
Total Assets,643256000000.0,624894000000.0,584626000000.0,554818000000.0,530969000000.0,NaN
Total Non Current Assets,458611000000.0,434027000000.0,408834000000.0,381511000000.0,366980000000.0,NaN
Other Non Current Assets,84246000000.0,73545000000.0,71309000000.0,63340000000.0,60947000000.0,NaN
Goodwill And Other Intangible Assets,23089000000.0,31676000000.0,23081000000.0,22879000000.0,22770000000.0,NaN
Other Intangible Assets,NaN,8602000000.0,NaN,NaN,NaN,7687000000.0
Goodwill,23089000000.0,23074000000.0,23081000000.0,22879000000.0,22770000000.0,NaN
Net PPE,351276000000.0,328806000000.0,314444000000.0,295292000000.0,283263000000.0,NaN
Accumulated Depreciation,NaN,-141390000000.0,NaN,NaN,NaN,-120111000000.0
Gross PPE,351276000000.0,470196000000.0,314444000000.0,295292000000.0,283263000000.0,NaN
Construction In Progress,NaN,46636000000.0,NaN,NaN,NaN,28840000000.0
Other Properties,351276000000.0,300521000000.0,314444000000.0,295292000000.0,283263000000.0,NaN
Land And Improvements,NaN,NaN,NaN,NaN,NaN,105293000000.0
Properties,NaN,123039000000.0,NaN,NaN,NaN,105293000000.0
Current Assets,184645000000.0,190867000000.0,175792000000.0,173307000000.0,163989000000.0,NaN
Other Current Assets,NaN,NaN,NaN,5906000000.0,5568000000.0,NaN
Inventory,35864000000.0,34214000000.0,36103000000.0,34109000000.0,31147000000.0,NaN
Inventories Adjustments Allowances,-2800000000.0,-3000000000.0,-2700000000.0,-2600000000.0,-2600000000.0,NaN
Other Inventories,38664000000.0,37214000000.0,38803000000.0,36709000000.0,33747000000.0,NaN
Receivables,54216000000.0,55451000000.0,51638000000.0,50106000000.0,47768000000.0,NaN
Other Receivables,NaN,NaN,NaN,3000000000.0,3100000000.0,NaN
Accounts Receivable,54216000000.0,55451000000.0,51638000000.0,50106000000.0,47768000000.0,NaN
Allowance For Doubtful Accounts Receivable,-2000000000.0,-2000000000.0,-1900000000.0,-1700000000.0,-1700000000.0,NaN
Gross Accounts Receivable,56216000000.0,57451000000.0,53538000000.0,51806000000.0,49468000000.0,NaN
Cash Cash Equivalents And Short Term Investments,94565000000.0,101202000000.0,88051000000.0,89092000000.0,85074000000.0,NaN
Other Short Term Investments,28358000000.0,22423000000.0,12960000000.0,17914000000.0,12222000000.0,NaN
Cash And Cash Equivalents,66207000000.0,78779000000.0,75091000000.0,71178000000.0,72852000000.0,NaN

In [14]:
dat.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m         18   48     4     0           0
1    -1m         18   47     4     0           0
2    -2m         21   46     4     0           0